"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path, os
from dotenv import load_dotenv
from django.contrib.messages import constants as messages


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = str(os.getenv('SECRET_KEY'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'




# Application definition

INSTALLED_APPS = [
    #'django.contrib.admin',# desativado — gestão via users-service
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.gestantes.apps.GestantesConfig',
    'apps.usuarios.apps.UsuariosConfig',
     'django_rq'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.usuarios.middleware.MicroserviceUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.global_variables', # Adiciona o context processor personalizado
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# =======================================================
# 🔧 CONFIGURAÇÃO DO BANCO DE DADOS (USANDO DOCKER + .env)
# =======================================================
# - As credenciais são lidas de variáveis de ambiente.
# - Facilita a troca de ambiente (dev, prod, teste).
# - Evita expor dados sensíveis no código.
# =======================================================

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'mydb'),
        'USER': os.getenv('DB_USER', 'user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'password'),
        'HOST': os.getenv('DB_HOST', 'db'),  # "db" = nome do serviço no docker-compose.yml
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',  # DEBUG mostra tudo
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'setup/static')
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Media

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
    messages.SUCCESS: 'success'
}


# Em desenvolvimento
#if DEBUG:
#    ALLOWED_HOSTS = ['localhost', '127.0.0.1','192.168.15.160','200.137.132.185']
# Em produção (DEBUG = False), você colocaria seu domínio real
#else:
#ALLOWED_HOSTS = ['www.integrai.ufma.br', 'integrai.ufma.br','200.137.132.185']
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

CSRF_TRUSTED_ORIGINS = os.getenv(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'https://integrai.ufma.br,https://www.integrai.ufma.br'
).split(',')


#ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")


#DATA_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024  # 5MB
#FILE_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024  # 5MB

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'

# Habilitar internacionalização e localização
USE_I18N = True
USE_TZ = True
USE_L10N = True



# Força o uso de formatação local (números, datas, moeda etc.)
USE_THOUSAND_SEPARATOR = True
DECIMAL_SEPARATOR = ','
THOUSAND_SEPARATOR = '.'


#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # só para testes
# EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, EMAIL_USE_TLS para produção


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')


# URL para redirecionar usuários não logados
LOGIN_URL = '/login/'  # substitua pelo caminho da sua view de login



# URL da API R (serviço 'r_api', porta 8000)
R_API_URL = os.environ.get('R_API_URL', 'http://predition_api:8000/predict')

MARIA_API_URL = os.getenv("MARIA_API_URL", "http://maria_api:8000")




# --- CONFIGURAÇÃO DO DJANGO-RQ (Lendo do 'environment' do Docker) ---

# Pega a URL do Redis da variável de ambiente
REDIS_URL = os.environ.get('REDIS_URL', 'redis://redis:6379/0')

RQ_QUEUES = {
    'default': {
        'URL': REDIS_URL,
        'DEFAULT_TIMEOUT': 360, # Timeout de 6 minutos por tarefa
        'DEFAULT_RESULT_TTL': 86400,  # <-- mantém os jobs por 24h
    }
}

# (Recomendado com Docker, como na minha sugestão anterior)
RQ_CONNECTOR_CLASS = 'django_rq.connectors.DjangoRedis'


CHAINLIT_URL = os.getenv("CHAINLIT_URL", "http://127.0.0.1:8080")

CHAINLIT_SECRET =  os.getenv("CHAINLIT_SECRET", "CHAINLIT_SECRET")

R_API_HEALTHCHECK_URL = "http://predition_api:8000/health"

# Usar modelo padrão do Django (não usa mais Usuario customizado local)
# AUTH_USER_MODEL = "usuarios.Usuario"  # Comentado - migrado para microservice

# Backend de autenticação - apenas microservice (sem fallback local)
AUTHENTICATION_BACKENDS = [
    'apps.usuarios.backends.MicroserviceBackend',
    # 'django.contrib.auth.backends.ModelBackend',  # Removido - não usa mais banco local
]
