# Generated by Django 5.1.2 on 2025-11-28 15:54

import apps.gestantes.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('peso', models.PositiveIntegerField(verbose_name='Peso pré-gestacional (kg)')),
                ('altura', models.FloatField(verbose_name='Altura (m)')),
                ('telefone', models.CharField(blank=True, help_text='Ex.: (83) 99999-1234', max_length=20, verbose_name='Telefone (preferencialmente WhatsApp)')),
                ('vulnerabilidade_social', models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Com base nas suas visitas domiciliares, você considera essa gestante em condição de vulnerabilidade social?')),
                ('foto', models.ImageField(blank=True, upload_to=apps.gestantes.models.Gestante.foto_upload_path)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestantes', to=settings.AUTH_USER_MODEL, verbose_name='Agente responsável')),
            ],
            options={
                'verbose_name': 'Gestante',
                'verbose_name_plural': 'Gestantes',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ConsentimentoGestante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('aceito', 'Aceito'), ('revogado', 'Revogado')], max_length=10)),
                ('motivo_revogacao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('gestante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos', to='gestantes.gestante')),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Avaliação')),
                ('peso_atual', models.FloatField(null=True, verbose_name='Peso atual:')),
                ('idade_gestacional', models.PositiveIntegerField(null=True, verbose_name='Idade Gestacional (em semanas)')),
                ('consultas_prenatal', models.PositiveIntegerField(null=True, verbose_name='Quantidade de consultas pré-natal')),
                ('corrimento_vaginal', models.BooleanField(default=False, verbose_name='Durante a gestação, você apresentou ou apresenta corrimento vaginal frequente?')),
                ('periodontite_carie', models.BooleanField(default=False, verbose_name='Você já teve cárie e/ou periodontite (inflamação na gengiva) diagnosticada nesta gestação?')),
                ('hipertensao_gestacao', models.BooleanField(default=False, verbose_name='Você foi diagnosticada com hipertensão (pressão alta) nesta gestação?')),
                ('diabetes_gestacao', models.BooleanField(default=False, verbose_name='Você foi diagnosticada com diabetes nesta gestação?')),
                ('estresse_gestacao', models.BooleanField(default=False, verbose_name='Você passou por algum estresse durante a gestação (violência, sobrecarga de trabalho)?')),
                ('historico_familiar_alergia', models.BooleanField(default=False, verbose_name='Algum membro da sua família (pai, mãe, irmãos) tem histórico de asma, rinite ou dermatite?')),
                ('consumo_bebidas_adocadas', models.BooleanField(default=False, verbose_name='Na última semana você consumiu refrigerante e outras bebidas industrializadas adoçadas artificialmente, como suco de caixinha, achocolatados, etc?')),
                ('consumo_ultraprocessados', models.BooleanField(default=False, verbose_name='Na última semana você consumiu alimentos ultraprocessados (ex.: sorvete, salgadinhos, salsicha, linguiça, presuntos, macarrão instantâneo, biscoitos recheados, etc)?')),
                ('consumo_alcool', models.BooleanField(default=False, verbose_name='Você consome/consumiu bebidas alcoólicas (cerveja, vinho, vodka, cachaça, etc) nesta gestação?')),
                ('fumante_gestacao', models.BooleanField(default=False, verbose_name='Você tinha o hábito de fumar ou fumou nesta gestação?')),
                ('resultado_integralidade_saude', models.JSONField(blank=True, null=True)),
                ('status_processamento_llm', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando LLM'), ('COMPLETED', 'LLM Concluído'), ('FAILED', 'LLM Falhou')], default='PENDING', max_length=20)),
                ('llm_sintese', models.TextField(blank=True, null=True, verbose_name='Síntese gerada pela LLM')),
                ('gestante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to='gestantes.gestante')),
            ],
            options={
                'verbose_name': 'Avaliacao',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['gestante', 'data_aplicacao'],
            },
        ),
        migrations.CreateModel(
            name='Pilula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Pílula')),
                ('conteudo', models.TextField(blank=True, null=True, verbose_name='Conteúdo da Pílula')),
                ('semana_num', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número da semana')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de envio')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('pendente', 'Pendente'), ('enviada', 'Enviada'), ('lida', 'Lida')], default='pendente', max_length=10)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilulas', to='gestantes.avaliacao')),
            ],
            options={
                'verbose_name': 'Pílula de Conhecimento',
                'verbose_name_plural': 'Pílulas de Conhecimento',
                'ordering': ['avaliacao', 'semana_num', 'data_geracao'],
            },
        ),
    ]
