# Generated by Django 5.1.2 on 2025-11-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='status_processamento_pills',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando LLM'), ('COMPLETED', 'LLM Concluído'), ('FAILED', 'LLM Falhou')], default='PENDING', max_length=20),
        ),
    ]
